/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthConversationsRouteImport } from './routes/_auth/conversations'
import { Route as AuthAgentsRouteImport } from './routes/_auth/agents'
import { Route as AuthSettingsIndexRouteImport } from './routes/_auth/settings/index'
import { Route as AuthAgentsIndexRouteImport } from './routes/_auth/agents/index'
import { Route as AuthSettingsSecurityRouteImport } from './routes/_auth/settings/security'
import { Route as AuthSettingsApiKeysRouteImport } from './routes/_auth/settings/api-keys'
import { Route as AuthSettingsVoiceRouteImport } from './routes/_auth/settings/voice'
import { Route as AuthSettingsAdminRouteImport } from './routes/_auth/settings/admin'
import { Route as AuthAgentsSlugRouteImport } from './routes/_auth/agents/$slug'
import { Route as AuthAgentsSlugIndexRouteImport } from './routes/_auth/agents/$slug/index'
import { Route as AuthAgentsSlugConversationsRouteImport } from './routes/_auth/agents/$slug/conversations'
import { Route as AuthAgentsSlugConversationsIdRouteImport } from './routes/_auth/agents/$slug/conversations/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthConversationsRoute = AuthConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAgentsRoute = AuthAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsIndexRoute = AuthSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthAgentsIndexRoute = AuthAgentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAgentsRoute,
} as any)
const AuthSettingsSecurityRoute = AuthSettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthSettingsApiKeysRoute = AuthSettingsApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthSettingsVoiceRoute = AuthSettingsVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthSettingsAdminRoute = AuthSettingsAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthAgentsSlugRoute = AuthAgentsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AuthAgentsRoute,
} as any)
const AuthAgentsSlugIndexRoute = AuthAgentsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAgentsSlugRoute,
} as any)
const AuthAgentsSlugConversationsRoute =
  AuthAgentsSlugConversationsRouteImport.update({
    id: '/conversations',
    path: '/conversations',
    getParentRoute: () => AuthAgentsSlugRoute,
  } as any)
const AuthAgentsSlugConversationsIdRoute =
  AuthAgentsSlugConversationsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthAgentsSlugConversationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/agents': typeof AuthAgentsRouteWithChildren
  '/conversations': typeof AuthConversationsRoute
  '/dashboard': typeof AuthDashboardRoute
  '/settings': typeof AuthSettingsRouteWithChildren
  '/agents/$slug': typeof AuthAgentsSlugRouteWithChildren
  '/settings/admin': typeof AuthSettingsAdminRoute
  '/settings/api-keys': typeof AuthSettingsApiKeysRoute
  '/settings/security': typeof AuthSettingsSecurityRoute
  '/settings/voice': typeof AuthSettingsVoiceRoute
  '/agents/': typeof AuthAgentsIndexRoute
  '/settings/': typeof AuthSettingsIndexRoute
  '/agents/$slug/conversations': typeof AuthAgentsSlugConversationsRouteWithChildren
  '/agents/$slug/': typeof AuthAgentsSlugIndexRoute
  '/agents/$slug/conversations/$id': typeof AuthAgentsSlugConversationsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/conversations': typeof AuthConversationsRoute
  '/dashboard': typeof AuthDashboardRoute
  '/settings/admin': typeof AuthSettingsAdminRoute
  '/settings/api-keys': typeof AuthSettingsApiKeysRoute
  '/settings/security': typeof AuthSettingsSecurityRoute
  '/settings/voice': typeof AuthSettingsVoiceRoute
  '/agents': typeof AuthAgentsIndexRoute
  '/settings': typeof AuthSettingsIndexRoute
  '/agents/$slug/conversations': typeof AuthAgentsSlugConversationsRouteWithChildren
  '/agents/$slug': typeof AuthAgentsSlugIndexRoute
  '/agents/$slug/conversations/$id': typeof AuthAgentsSlugConversationsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/agents': typeof AuthAgentsRouteWithChildren
  '/_auth/conversations': typeof AuthConversationsRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/settings': typeof AuthSettingsRouteWithChildren
  '/_auth/agents/$slug': typeof AuthAgentsSlugRouteWithChildren
  '/_auth/settings/admin': typeof AuthSettingsAdminRoute
  '/_auth/settings/api-keys': typeof AuthSettingsApiKeysRoute
  '/_auth/settings/security': typeof AuthSettingsSecurityRoute
  '/_auth/settings/voice': typeof AuthSettingsVoiceRoute
  '/_auth/agents/': typeof AuthAgentsIndexRoute
  '/_auth/settings/': typeof AuthSettingsIndexRoute
  '/_auth/agents/$slug/conversations': typeof AuthAgentsSlugConversationsRouteWithChildren
  '/_auth/agents/$slug/': typeof AuthAgentsSlugIndexRoute
  '/_auth/agents/$slug/conversations/$id': typeof AuthAgentsSlugConversationsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/agents'
    | '/conversations'
    | '/dashboard'
    | '/settings'
    | '/agents/$slug'
    | '/settings/admin'
    | '/settings/api-keys'
    | '/settings/security'
    | '/settings/voice'
    | '/agents/'
    | '/settings/'
    | '/agents/$slug/conversations'
    | '/agents/$slug/'
    | '/agents/$slug/conversations/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/conversations'
    | '/dashboard'
    | '/settings/admin'
    | '/settings/api-keys'
    | '/settings/security'
    | '/settings/voice'
    | '/agents'
    | '/settings'
    | '/agents/$slug/conversations'
    | '/agents/$slug'
    | '/agents/$slug/conversations/$id'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/agents'
    | '/_auth/conversations'
    | '/_auth/dashboard'
    | '/_auth/settings'
    | '/_auth/agents/$slug'
    | '/_auth/settings/admin'
    | '/_auth/settings/api-keys'
    | '/_auth/settings/security'
    | '/_auth/settings/voice'
    | '/_auth/agents/'
    | '/_auth/settings/'
    | '/_auth/agents/$slug/conversations'
    | '/_auth/agents/$slug/'
    | '/_auth/agents/$slug/conversations/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/conversations': {
      id: '/_auth/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof AuthConversationsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/agents': {
      id: '/_auth/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthAgentsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/': {
      id: '/_auth/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthSettingsIndexRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/agents/': {
      id: '/_auth/agents/'
      path: '/'
      fullPath: '/agents/'
      preLoaderRoute: typeof AuthAgentsIndexRouteImport
      parentRoute: typeof AuthAgentsRoute
    }
    '/_auth/settings/security': {
      id: '/_auth/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthSettingsSecurityRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/api-keys': {
      id: '/_auth/settings/api-keys'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof AuthSettingsApiKeysRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/voice': {
      id: '/_auth/settings/voice'
      path: '/voice'
      fullPath: '/settings/voice'
      preLoaderRoute: typeof AuthSettingsVoiceRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/admin': {
      id: '/_auth/settings/admin'
      path: '/admin'
      fullPath: '/settings/admin'
      preLoaderRoute: typeof AuthSettingsAdminRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/agents/$slug': {
      id: '/_auth/agents/$slug'
      path: '/$slug'
      fullPath: '/agents/$slug'
      preLoaderRoute: typeof AuthAgentsSlugRouteImport
      parentRoute: typeof AuthAgentsRoute
    }
    '/_auth/agents/$slug/': {
      id: '/_auth/agents/$slug/'
      path: '/'
      fullPath: '/agents/$slug/'
      preLoaderRoute: typeof AuthAgentsSlugIndexRouteImport
      parentRoute: typeof AuthAgentsSlugRoute
    }
    '/_auth/agents/$slug/conversations': {
      id: '/_auth/agents/$slug/conversations'
      path: '/conversations'
      fullPath: '/agents/$slug/conversations'
      preLoaderRoute: typeof AuthAgentsSlugConversationsRouteImport
      parentRoute: typeof AuthAgentsSlugRoute
    }
    '/_auth/agents/$slug/conversations/$id': {
      id: '/_auth/agents/$slug/conversations/$id'
      path: '/$id'
      fullPath: '/agents/$slug/conversations/$id'
      preLoaderRoute: typeof AuthAgentsSlugConversationsIdRouteImport
      parentRoute: typeof AuthAgentsSlugConversationsRoute
    }
  }
}

interface AuthAgentsSlugConversationsRouteChildren {
  AuthAgentsSlugConversationsIdRoute: typeof AuthAgentsSlugConversationsIdRoute
}

const AuthAgentsSlugConversationsRouteChildren: AuthAgentsSlugConversationsRouteChildren =
  {
    AuthAgentsSlugConversationsIdRoute: AuthAgentsSlugConversationsIdRoute,
  }

const AuthAgentsSlugConversationsRouteWithChildren =
  AuthAgentsSlugConversationsRoute._addFileChildren(
    AuthAgentsSlugConversationsRouteChildren,
  )

interface AuthAgentsSlugRouteChildren {
  AuthAgentsSlugConversationsRoute: typeof AuthAgentsSlugConversationsRouteWithChildren
  AuthAgentsSlugIndexRoute: typeof AuthAgentsSlugIndexRoute
}

const AuthAgentsSlugRouteChildren: AuthAgentsSlugRouteChildren = {
  AuthAgentsSlugConversationsRoute:
    AuthAgentsSlugConversationsRouteWithChildren,
  AuthAgentsSlugIndexRoute: AuthAgentsSlugIndexRoute,
}

const AuthAgentsSlugRouteWithChildren = AuthAgentsSlugRoute._addFileChildren(
  AuthAgentsSlugRouteChildren,
)

interface AuthAgentsRouteChildren {
  AuthAgentsSlugRoute: typeof AuthAgentsSlugRouteWithChildren
  AuthAgentsIndexRoute: typeof AuthAgentsIndexRoute
}

const AuthAgentsRouteChildren: AuthAgentsRouteChildren = {
  AuthAgentsSlugRoute: AuthAgentsSlugRouteWithChildren,
  AuthAgentsIndexRoute: AuthAgentsIndexRoute,
}

const AuthAgentsRouteWithChildren = AuthAgentsRoute._addFileChildren(
  AuthAgentsRouteChildren,
)

interface AuthSettingsRouteChildren {
  AuthSettingsAdminRoute: typeof AuthSettingsAdminRoute
  AuthSettingsApiKeysRoute: typeof AuthSettingsApiKeysRoute
  AuthSettingsSecurityRoute: typeof AuthSettingsSecurityRoute
  AuthSettingsVoiceRoute: typeof AuthSettingsVoiceRoute
  AuthSettingsIndexRoute: typeof AuthSettingsIndexRoute
}

const AuthSettingsRouteChildren: AuthSettingsRouteChildren = {
  AuthSettingsAdminRoute: AuthSettingsAdminRoute,
  AuthSettingsApiKeysRoute: AuthSettingsApiKeysRoute,
  AuthSettingsSecurityRoute: AuthSettingsSecurityRoute,
  AuthSettingsVoiceRoute: AuthSettingsVoiceRoute,
  AuthSettingsIndexRoute: AuthSettingsIndexRoute,
}

const AuthSettingsRouteWithChildren = AuthSettingsRoute._addFileChildren(
  AuthSettingsRouteChildren,
)

interface AuthRouteChildren {
  AuthAgentsRoute: typeof AuthAgentsRouteWithChildren
  AuthConversationsRoute: typeof AuthConversationsRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthSettingsRoute: typeof AuthSettingsRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAgentsRoute: AuthAgentsRouteWithChildren,
  AuthConversationsRoute: AuthConversationsRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthSettingsRoute: AuthSettingsRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
